# Generated by Django 5.0.6 on 2024-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubirDocumentoImagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('documento', models.FileField(upload_to='documents/')),
            ],
            options={
                'db_table': 'libreria_libro',
                'managed': False,
            },
        ),
    ]
